workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      ios_signing:
        provisioning_profiles:
          - Workout Tracker
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Build and Archive
        script: |
          xcodebuild -project "Workout Tracker.xcodeproj" -scheme "Workout Tracker" -configuration Release -derivedDataPath build -archivePath build/Workout.xcarchive -allowProvisioningUpdates archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath build/Workout.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ipa -allowProvisioningUpdates
    artifacts:
      - build/ipa/**/*.ipa
    publishing:
      app_store_connect:
        auth: api_key
        bundle_id: com.pieksandrvoloshko.workouttracker
