workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: RemoteXAPI
    environment:
      xcode: latest
      ios_signing:
        provisioning_profiles:
          - com.workout.tracker.Workout-Tracker
      vars:
        DEVELOPMENT_TEAM: 5A299U4MF6   # 👈 ДОБАВИЛИ ТОЛЬКО ЭТО
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Build and Archive
        script: |
          xcodebuild -project "Workout Tracker.xcodeproj" -scheme "Workout Tracker" -configuration Release -derivedDataPath build -archivePath build/Workout.xcarchive -allowProvisioningUpdates DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath build/Workout.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ipa -allowProvisioningUpdates
    artifacts:
      - build/ipa/**/*.ipa
    publishing:
      app_store_connect:
        auth: integration
